### ISSUE TITLE
The relative path "../soln.py" works inconsistently on Mac and Windows platforms

### ISSUE THREAD

**Issue by ahmetuysal** [csbridge/csbridge2020#3]
The relative path "../soln.py" fails on Mac because ".." goes one directory up. 
_Originally posted by @yanlisa in https://github.com/csbridge/csbridge2020/pull/1#issuecomment-664100937_

I will try to find which causes this issue and try to fix it.

**Comment by ahmetuysal** [comment]
I managed to find the source of problem. `projectTemplate.ptl` files included OS specific logic to construct the path of solution file. It should be fine for both platforms now, but can you verify it is working for MacOS as well @yanlisa. Also, you should be careful not to include previous faulty logic in cz template for `projectTemplate.ptl`.

**Comment by yanlisa** [comment]
Thank you Ceren and Ahmet!
