### ISSUE TITLE
Console Bonus Translation Update Needed

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#33]
`templates/tr/projects/consoleBonus.md` is mostly up to date (it is a combination of several older separate problems.  The only part that needs re-translating is the note at the very top, and the FizzBuzz problem, which changed.  The old translated version is in `templates/tr/projects/fizzbuzz.mdown`.  Is someone able to take a look? Thank you!

**Comment by ckocaogullar** [comment]
Done! #34
