### ISSUE TITLE
Area Calculator Translation Update Needed

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#35]
We made a few last-minute changes to the Area Calculator quickstart problem.  A good chunk of it is unchanged, but there are some edits that you can see [in this commit here](https://github.com/csbridge/csbridge2020/commit/01e7ebbf4a139ff5a5cf104d6ad1f02739dce2a0#diff-5665f2bc922d4339455261e129996687).  (The commit contains many files because of the recompile, so you may need to wait a second for the full page to load, and then it should jump down to the file `templates/en/projects/areaCalculator.mdown` and show you its changes).  Is someone able to take a look? Thank you!

**Comment by ckocaogullar** [comment]
Done! #36
