### ISSUE TITLE
Day 5 Translation Updates

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#37]
We just finished posting the projects for day 5 (Mon.).  There were a few minor updates that were made, and I'd appreciate anyone taking a quick look at a few of the places below where we made changes that need translation updates.

**Funky Functions**
This problem is a combination of past problems.  A good chunk is the same, but there were minor tweaks to the problems, highlighted in [this commit](https://github.com/csbridge/csbridge2020/commit/d3a76cb22e8e590ded258e04802a3f6ca01fbc1a#diff-2b).  These portions were replaced in English in the Turkish version as well.

Relevant file: `templates/tr/projects/funkyFunctions.mdown`

**Fizz Buzz**
This problem also had minor updates, mostly the new note at the top.  See [this commit](https://github.com/csbridge/csbridge2020/commit/d3a76cb22e8e590ded258e04802a3f6ca01fbc1a#diff-2b).

Relevant file: `templates/tr/project/fizzbuzz-functions.md`

Finally, the project table on the main screen is mostly translated, except for one new string, "Graphics and Randomness", which is the problem topic for random circles.  If someone could open `templates/programs/programs.json` and add a translation for that for the random circles problem, that would be awesome.

One last note in need of translation - there is one bonus program "More Functions" that is new and doesn't have a translation yet.  The relevant file is `templates/tr/project/moreFunctions.md`.  (This is lower priority).

Thank you!

**Comment by ckocaogullar** [comment]
Done! #39
