### ISSUE TITLE
Day 6 Translation Updates

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#38]
We just finished posting the projects for day 6 (Tues.). There were a few minor updates that were made, and I'd appreciate anyone taking a quick look at a few of the places below where we made changes that need translation updates.

**Print Indices**
This is a new problem in the morning that needs to be translated.  The file is currently in English at `templates/tr/projects/printIndices.md`.  It would also be great if someone could update `templates/programs/programs.json` with the Turkish translation for the problem title.  Thank you!

**Optical Illusion**
This problem is mostly the same, but had minor wording tweaks.  The commit with the updates [is here](https://github.com/csbridge/csbridge2020/commit/8bbefd2c51ff567b0524156bb54d611cf5908a7c#diff-e1a323bd2fee6aaf4918c93794a92b14).

**Bouncing Ball**
This problem also had minor wording tweaks.  The commit with the updates [is here](https://github.com/csbridge/csbridge2020/commit/2f1c80392989b7ebd28abfaae68d2b2bf3810b49#diff-e5167c7c2a4202bffab7d52f0c69708b).

**Short Film**
Short Film was the last problem to get minor wording tweaks.  The commit with the updates [is here](https://github.com/csbridge/csbridge2020/commit/47df5f53e468652c81c77dd9c9b02f6f7c33caa2#diff-9f1848ddec51dffc17e8d88b59bbc8d5).

**Comment by ckocaogullar** [comment]
Done! #40
