### ISSUE TITLE
Day 7 Updates Needing Translation

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#45]
We just finalized day 7 materials and there are a few changes that need re-translation:

- there is a new problem in the morning, "Ascending Numbers", that needs to be translated.  The relevant file is here: `templates/tr/projects/ascending.md`.  If you could also update the translated name in `templates/programs/programs.json` that would be awesome.

- there is a new problem in the evening, "Mouse Location", that needs to be translated.  The relevant file is here: `templates/tr/projects/mouseLocation.md`.  If you could also update the translated name in `templates/programs/programs.json` that would be awesome.

- in Making Tracks the evening section problem, we added a new note about Pillow installation - could someone take a look at translating that?  The relevant commit with the change [is here](https://github.com/csbridge/csbridge2020/commit/6814134f0fcac2b34cf1c5d2b8aa60661a51dc7c#diff-7e682333364dfca83325b0ab2a6fbd15).

- there is a new problem in the evening, "Catch Me If You Can", that needs to be translated.  The relevant file is here: `templates/tr/projects/catchMeIfYouCan.mdown`.  If you could also update the translated name in `templates/programs/programs.json` that would be awesome.

- there is a worked example in the evening, Debris Sweeper, that had small updates.  The relevant commit with the change [is here](https://github.com/csbridge/csbridge2020/commit/57c4ddc3b58112d40bd466a8d143de4565b01e89#diff-f42d9342a596c27c48de01b1d0306835)

- there is a new worked example in the evening, Rocket Paddle, that needs to be translated.  The relevant file is here: `templates/tr/projects/rocketPaddle/index.md`.  If you could also update the translated name in `templates/programs/programs.json` that would be awesome.

Finally, how do you say "Lists and Mouse" in Turkish? 😅 That's the listed topic for day 7.  Could someone update the translated name for day 7 in `templates/programs/programs.json`?

**Comment by ckocaogullar** [comment]
Done! #46
