### ISSUE TITLE
Breakout Minor Updates

### ISSUE THREAD

**Issue by Nickster28** [csbridge/csbridge2020#47]
We just finalized the spec and made a few small changes - see [this commit](https://github.com/csbridge/csbridge2020/commit/52b09ea3bb858402598128ca19c7bd333982bd05#diff-93fec76eceb3dedd791eff2488d66c8b).  Is someone able to update the Turkish translation with these changes?  Thank you!

**Comment by ckocaogullar** [comment]
Done! #48
